### ISSUE TITLE
Deployment happens even if I don't change the function

### ISSUE THREAD

**Issue by ummwolfcat** [apex/apex#322]
Every time I run "apex deploy" a new version of the function gets pushed to Lambda — even If I didn't change anything. From the documentation it says, "Apex performs a checksum to see if the deployed function matches the local build, if so it’s not deployed" So I'm not sure why this is happening?

I did a "apex build" after each deploy at one point to see if, somehow, the two zips were indeed different, but they were not.

**Comment by tj** [comment]
Could you paste the `--log-level debug` output? This is with v0.7.0?

**Comment by ummwolfcat** [comment]
Yeah, 0.7.0. Here's the paste:
https://gist.github.com/ummwolfcat/9cedf489363677c45f65

I'm nearly certain it was working properly when I first started — no idea what would have changed to cause this.

**Comment by tj** [comment]
Ah right we fixed that regression here: fb06f288 – I'll do a patch release tonight so there's a new binary up, sorry about that!

**Comment by ummwolfcat** [comment]
@tj I'm still seeing v0.7.0 as the latest release — have you had a chance to do that patch release?

**Comment by tj** [comment]
@ummwolfcat sorry about that! forgot, uploading the bins now

**Comment by tj** [comment]
technically should be v0.8.0, too lazy to maintain a v0.7.x branch for that stuff so it has the small feature additions as well :D

**Comment by ummwolfcat** [comment]
Yay it works now! Thanks! :D
